name: Sync Discord Channels

on:
  push:
    branches:
      - main
  schedule:
    - cron: '1 */6 * * *'  

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py requests

      - name: Run sync script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          WEBHOOK_URL_SERVER_1: ${{ secrets.WEBHOOK_URL_SERVER_1 }}
          WEBHOOK_URL_SERVER_2: ${{ secrets.WEBHOOK_URL_SERVER_2 }}
          CHANNEL_ID_SERVER_1: ${{ secrets.CHANNEL_ID_SERVER_1 }}
          CHANNEL_ID_SERVER_2: ${{ secrets.CHANNEL_ID_SERVER_2 }}
        run: python bot.py
