name: Sync Discord Channels

on:
  push:
    branches:
      - main
  schedule:
    - cron: '2 */6 * * *'  

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install python3.12
          pip install discord.py requests

      - name: Run sync script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          WEBHOOK_URL_SERVER_1: ${{ secrets.WEBHOOK_URL_SERVER_1 }}
          WEBHOOK_URL_SERVER_2: ${{ secrets.WEBHOOK_URL_SERVER_2 }}
          CHANNEL_ID_SERVER_1: ${{ secrets.CHANNEL_ID_SERVER_1 }}
          CHANNEL_ID_SERVER_2: ${{ secrets.CHANNEL_ID_SERVER_2 }}
          WEBHOOK_URL_SERVER_3: ${{ secrets.WEBHOOK_URL_SERVER_3 }}
          CHANNEL_ID_SERVER_3: ${{ secrets.CHANNEL_ID_SERVER_3 }}
        run: python bot.py
